name: delete terraftom module
description: used to delete a terrafrom module in an organization
inputs:
  token:
    description: terraform user token
    required: true
  module_name:
    description: the name of the terraform module to be deleted 
    required: true
  provider:
    description: the module provider | aws
    required: true
  registry_name:
    description: private | public registry
    required: true
  organization:
    description: the terrafrom cloud module organization 
    required: true
outputs:
  response:
    description: request response
runs:
  using: node12
  main: dist/index.js
